# Generated by Django 4.1.4 on 2022-12-25 01:52

import app.models.ParticipantModel
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('surname', models.TextField()),
                ('name', models.TextField()),
                ('patronymic', models.TextField()),
                ('post', models.TextField()),
                ('passport_data', models.TextField()),
                ('register_of_specialists', models.IntegerField()),
                ('ogrn', models.TextField()),
                ('inn', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('legal_name', models.TextField()),
                ('details_admin_doc', models.TextField()),
                ('participant_type', enumchoicefield.fields.EnumChoiceField(default=app.models.ParticipantModel.ParticipantModel.ParticipantType['OTHER'], enum_class=app.models.ParticipantModel.ParticipantModel.ParticipantType, max_length=14)),
                ('subject_type', enumchoicefield.fields.EnumChoiceField(default=app.models.ParticipantModel.ParticipantModel.SubjectType['NATURAL_PERSON'], enum_class=app.models.ParticipantModel.ParticipantModel.SubjectType, max_length=23)),
            ],
            options={
                'db_table': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('certificate', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.participantmodel')),
            ],
            options={
                'db_table': 'Materials',
            },
        ),
    ]
