# Generated by Django 4.1.4 on 2023-01-04 09:56

from django.db import migrations

def add_test_participant(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Participant = apps.get_model('app', 'ParticipantModel')
    Participant.objects.create(
        surname="Титов",
        name="Павел",
        register_of_specialists=1,
        ogrn="1026605606620",
        inn="1707083893",
    ).save()
    Participant.objects.create(
        surname="Шемякин",
        name="Илья",
        register_of_specialists=2,
        ogrn="2026605606620",
        inn="2707083893",
    ).save()
    # Participant.objects.create(
    #     surname="Атаханова",
    #     name="Анна",
    #     register_of_specialists=3,
    # )
    # Participant.objects.create(
    #     surname="Петрищев",
    #     name="Сергей",
    #     register_of_specialists=4,
    # )

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [migrations.RunPython(add_test_participant)]
